Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/authentication_controller.rb, app/controllers/concerns/json_web_token.rb, app/controllers/users_controller.rb, app/models/user.rb, config/application.rb, config/routes.rb, db/migrate/20230314162745_fix_user_password_name.rb, db/schema.rb, lib/json_web_token.rb
* Add jwt gem
* add JsonWebToken.rb in /lib
* tokens set to expire in 3 days
=> Alexis - incorporate JWT userAuth

.gitignore, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/controllers/workouts_controller.rb, config/application.rb, db/migrate/20230309234134_create_users.rb, db/seeds.rb, lib/json_web_token.rb
ability to create workouts
POST /workout/ will calculate points using hardcoded game settings (intensity_points and activity_points) and save workout with points
=> workout controller point calculation

api/app/controllers/application_controller.rb, api/app/controllers/authentication_controller.rb, api/app/models/blacklisted_token.rb, api/config/routes.rb, api/db/migrate/20230323160643_create_blacklisted_tokens.rb, api/lib/activity_points.rb
adding route to logout
on logout, jwt added to blacklist table
=> jwt logout by blacklisting tokens

api/Gemfile.lock, client/Dockerfile, client/vite.config.js, docker-compose.yml
docker-compose.yml - update docker compose so that volume is generated correctly. This mounts the codebase to docker container so that changes to the code base will not require rebuild each time. 
Added vite client service back into docker-compose
vite.config - updated so that it works with Docker
=> update Dockerfile to mount volume. Configure vite to run within docker

api/app/controllers/authentication_controller.rb, api/app/controllers/users_controller.rb, api/config/routes.rb, client/src/app/api/apiSlice.js, client/src/pages/account/Profile.css, client/src/pages/account/Profile.jsx, client/src/pages/auth/Login.jsx, client/src/pages/newcompetition/Create.jsx, client/src/store/auth/userSlice.js, client/src/store/game/participantSlice.js, client/src/store/game/participantsApiSlice.js, docker-compose.yml
1. Upon authentication from auth/login, json returned includes user workouts and competitions (re-added)
2. Add cors pre-flight check to /users endpoint
3. Update base query in apiSlice
4. Add workouts and competitions to localStorage so that data persists on refresh
5. Add participant slice which fetches /users and stores in state 
6. Updated DockerCompose so that db is created in correct directory
=> Create Competition edits

api/app/controllers/application_controller.rb, api/app/controllers/authentication_controller.rb, api/app/controllers/users_controller.rb, api/config/routes.rb, client/src/pages/tournaments/Feed.jsx, client/src/pages/tournaments/Leaderboard.jsx, client/src/pages/tournaments/Record.jsx, client/src/pages/tournaments/TournamentPage.jsx, client/src/store/game/leaderboardApiSlice.js, client/src/store/game/leaderboardSlice.js, client/src/store/game/workoutApiSlice.js
1. Move cors_pre_flight check to application controller (from authentication controller);
2. Update routes to match options
3. Client render leaderboard
4. Post workout feature
=> render leaderboard and post workout

api/app/controllers/workouts_controller.rb, client/src/pages/tournaments/Leaderboard.jsx, client/src/pages/tournaments/Record.jsx
in the method workout_params included params.require(:workout) to ensure the hash contains a workout key
=> small bug fix with unpermitted params

api/app/controllers/authentication_controller.rb, api/app/controllers/users_controller.rb, api/app/models/user.rb, api/config/routes.rb, client/src/pages/account/EditProfileModal.jsx, client/src/pages/account/Profile.css, client/src/pages/account/Profile.jsx, client/src/pages/auth/Login.css, client/src/pages/auth/Login.jsx, client/src/pages/auth/Signup.css, client/src/pages/auth/Signup.jsx, client/src/pages/newcompetition/NewCompetition.jsx, client/src/store/auth/authApiSlice.js, client/src/store/auth/userSlice.js
1. Add additional permitted parameters to authentication controller for sign up
2. Move location of sign up form toggle between sign up and login
3. Add additional input tags to sign up form
=> add additional fields to sign up form

api/app/controllers/competitions_controller.rb, api/app/controllers/posts_controller.rb, api/app/models/competition.rb, client/src/app/store.js, client/src/pages/account/Profile.jsx, client/src/pages/tournaments/Feed.jsx, client/src/pages/tournaments/PostCard.jsx, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/TournamentPage.jsx, client/src/store/game/competitionApiSlice.js, client/src/store/game/feedApiSlice.js, client/src/store/game/feedSlice.js, docker-compose.yml
1. Fetched all posts that belong to particular competition
2. Created PostCard component
3. Added index to the PostsController
=> Posts fetched and rendered to the Competition page

api/app/controllers/posts_controller.rb, client/src/pages/tournaments/Feed.jsx, client/src/pages/tournaments/PostCard.jsx, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/TournamentPage.jsx, client/src/store/game/feedSlice.js
1. Users can add posts to the feed
2. create method added to the posts controller
3. used refetch to rerender feed
=> created Add Post to the Feed

api/app/controllers/workouts_controller.rb, client/src/pages/tournaments/CompetitionPage.css, client/src/pages/tournaments/Feed.jsx, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/Record.jsx, client/src/pages/tournaments/TournamentPage.jsx, docker-compose.yml
1. When user creates a workout, workout controller will also create a post that reads: "user just posted a workout! [cycling] for [25]mins, earning [120] points!"
2. Updated post will render to the Competition Feed
=> creating workout also creates a post

api/app/controllers/workouts_controller.rb, api/app/serializers/competition_serializer.rb, api/db/seeds.rb, client/src/pages/auth/Login.jsx, client/src/pages/auth/Signup.jsx, client/src/pages/tournaments/CompetitionPage.css, client/src/pages/tournaments/Feed.jsx, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/Record.jsx, client/src/pages/tournaments/TournamentPage.jsx, docker-compose.yml
This PR addresses issue #55 
Workout input dates have a min value: date of when competition was created and a max value: today
Competition serializer updated to include created_at
Seed values updated to fix created_at dates for seed competitions
=> Record new workout date validation

api/app/controllers/competitions_controller.rb, api/config/routes.rb, client/src/App.jsx, client/src/pages/newcompetition/Join.jsx, client/src/pages/newcompetition/JoinCompetition.jsx, client/src/store/game/competitionApiSlice.js, client/src/store/game/competitionSlice.js
User is able to search competition by identifier and join the competition if it exists and user is not already in the competition
=> Build join a competition

client/package-lock.json, client/package.json, client/src/components/Header.css, client/src/components/Header.jsx, client/src/components/HeaderOption.css, client/src/components/HeaderOption.jsx, client/src/components/Main.jsx, client/src/pages/account/Profile.css, client/src/pages/account/Profile.jsx, client/src/pages/account/Sidebar.css, client/src/pages/account/Sidebar.jsx
Added material UI as dependencies.
=> added Profile icons, Header, and Sidebar

client/src/pages/account/Profile.css, client/src/pages/account/Profile.jsx
Only changes:
Lines 147 & 148 in Profile.css
Line 29 in Profile.jsx
Other changes are indentation/formatting
=> wrap curr competition icons and fix width

client/src/pages/account/EditProfileModal.jsx, client/src/pages/account/Profile.jsx
1. After user has finished editing modal, and clicks update, modal will close - achieved by calling the callback function closeEditProfileModal within the onSubmit
2. If user clicks anywhere outside of the modal, the modal will close - achieved by using useEffect and adding event listener on the window object
=> fix close modal bug issue #57

client/src/App.jsx, client/src/components/Header.css, client/src/components/Header.jsx, client/src/components/Layout.jsx, client/src/pages/account/Profile.jsx, client/src/pages/auth/Authorization.jsx, client/src/pages/auth/RequireAuth.jsx, client/src/pages/tournaments/TournamentPage.jsx
1. User cannot go back after logout #66 
2. Navbar fixed and route to home added #65
=> Fixed logout and Navbar fix

client/src/pages/newcompetition/CreateCompetition.jsx
=> Add start and end date validations 

api/app/controllers/workouts_controller.rb, client/src/pages/account/Profile.jsx, client/src/pages/account/RecentWorkouts.jsx, client/src/pages/account/Sidebar.jsx, client/src/pages/auth/Login.jsx, client/src/pages/newcompetition/CreateCompetition.jsx, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/TournamentPage.jsx, client/src/store/auth/userSlice.js, client/src/store/game/competitionSlice.js, client/src/store/game/workoutApiSlice.js, client/src/store/game/workoutSlice.js
1. After creating a new competition, client will redirect to the profile page;
2. When refreshing on the profile page, competition information will be refetched;
3. User workout and user competition no longer stored in localstorage;
4. Other tidy ups
=> creating a new competition will redirect to profile page

api/app/controllers/application_controller.rb, api/app/controllers/users_controller.rb, api/app/controllers/workouts_controller.rb, api/config/routes.rb, client/src/pages/account/EditProfileModal.jsx, client/src/pages/account/Profile.jsx, client/src/pages/account/RecentWorkouts.jsx, client/src/pages/account/Sidebar.jsx, client/src/pages/auth/Login.jsx, client/src/pages/newcompetition/CreateCompetition.jsx, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/Record.jsx, client/src/pages/tournaments/TournamentPage.jsx, client/src/store/auth/authApiSlice.js, client/src/store/auth/userSlice.js, client/src/store/game/competitionSlice.js, client/src/store/game/workoutApiSlice.js, client/src/store/game/workoutSlice.js
1. Add authentication requirement to the following routers:
* PATCH /users
* GET /workouts
* POST /workouts
2. Client sends jwt to backend via authorization headers. This is achieved via base query in apislice
3. Before actioning above methods, rails will authenticate user
=> Add authentication headers to crud requests

api/app/controllers/posts_controller.rb, client/src/pages/newcompetition/Join.jsx, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/Record.jsx
1. added "before_action: authenticate_request, only: [:create, :destroy]" to POSTS CONTROLLER
2. 2. Issue  #79  fixed! Refetch() added after saving workout and joining competition!
=> added authenticate to post controller and refetched after CRUD

client/src/components/Main.css
=> increase height of banner--fadeBottom

api/app/models/workout.rb, api/app/serializers/competition_serializer.rb, api/db/seeds.rb, client/src/pages/account/MainFeed.css, client/src/pages/account/RecentWorkouts.jsx, client/src/pages/tournaments/TournamentPage.jsx
1. Add validations to creating workouts;
2. Update serializers for competitions;
3. Add date of workout to recent workouts table;
4. Add remaining days to tournament header;
=> render dates to competition page

client/src/app/store.js, client/src/pages/account/Profile.jsx, client/src/pages/account/RecentWorkouts.jsx, client/src/pages/account/Sidebar.jsx, client/src/store/game/competitionSlice.js
* Cleaned up imports in Profile.jsx
* Updated competitionSlice to set competition state correctly
* Updated sidebar so that number of competitions and workouts display correctly and persist upon refresh
* Address Issue #87
=> fix workout numbers in sidebar

client/src/pages/account/Sidebar.jsx, client/src/pages/newcompetition/CreateCompetition.jsx
1. Add current user as a default participant to creating a competition;
2. Use addCompetition reducer to update competition state;
3. When creating a competition, user that is logged in will automatically be selected and disabled by default
=> Add creator to new comp by default v2

api/app/controllers/competitions_controller.rb, client/src/pages/account/Sidebar.jsx, client/src/pages/newcompetition/CreateCompetition.jsx
This PR addresses Issue #90 
Added start_date and end_date to comp_params
Error was created because end date passed from client did not align with competition controller and so the end date was not being created.
=> Fix dates on new comps

api/app/controllers/application_controller.rb, api/app/controllers/competitions_controller.rb, api/app/controllers/users_controller.rb, api/db/migrate/20230502203009_add_type_to_user.rb, api/db/schema.rb, api/db/seeds.rb, client/src/pages/account/Sidebar.jsx, client/src/pages/newcompetition/CreateCompetition.jsx
1. Creating a competition will also create an admin_bot as a user, with user_type: "bot",
2. Added migration to add user_type to User;
3. Updated seeds.rb file;
4. Creating a competition also adds admin_bot as a participant along with a post for the creation of the competition, and a post for each participant joining the comp
=> Create admin bot

api/app/controllers/workouts_controller.rb, client/src/pages/account/RecentWorkouts.jsx
1. Fixed leaderboard update after delete Issue 1 in #88
=> Fixed leaderBoard update after deleting workout

api/app/controllers/workouts_controller.rb, client/src/pages/account/RecentWorkouts.jsx
1. Changed post user to competition bot when new workout added
=> New workout posted user changed to bot

api/app/controllers/friendships_controller.rb, api/app/controllers/users_controller.rb, api/app/models/friendship.rb, api/app/models/user.rb, api/config/routes.rb, client/src/pages/friend/FriendsPage.jsx, client/src/pages/friend/PendingFriendCard.jsx, client/src/pages/friend/SearchFriendResult.jsx, client/src/store/auth/authApiSlice.js, client/src/store/social/friendApiSlice.js
=> build friendships - request, ignore, accept, delete

client/src/components/Header.css, client/src/components/Header.jsx, client/src/components/HeaderOption.css, client/src/pages/account/Profile.css, client/src/pages/account/Profile.jsx, client/src/pages/account/RecentWorkouts.jsx, client/src/pages/account/Sidebar.css, client/src/pages/account/Sidebar.jsx
Add popup to profile avatar 
Moved Logout button from sidebar to popup
=> style header

api/app/models/friendship.rb
-  Added validation in the friendships controller, user's now cannot remove a friend if both of them are in an active competition if the competition is private.
=> added validation to removing friends

client/src/components/Header.css, client/src/index.css, client/src/pages/account/CompetitionCard.css, client/src/pages/account/InputOption.css, client/src/pages/account/MainFeed.css, client/src/pages/account/Profile.css, client/src/pages/account/Sidebar.css, client/src/pages/tournaments/CompetitionPage.css
started mobile styling for the profile component
=> started mobile styling

client/src/pages/account/CompetitionCard.css, client/src/pages/account/MainFeed.css
Added flex wrap to current competitions container on profile page
=> Style profile page

api/config/initializers/cors.rb, api/config/routes.rb, client/src/components/Header.jsx, client/src/pages/account/CompetitionCard.jsx, client/src/pages/account/Sidebar.css, client/src/pages/account/Sidebar.jsx, client/src/pages/friend/FriendCard.css, client/src/pages/friend/FriendCard.jsx, client/src/pages/friend/FriendsPage.css, client/src/pages/friend/FriendsPage.jsx, client/src/pages/friend/PendingFriendCard.jsx, client/src/pages/friend/SearchFriendResult.jsx, client/src/pages/newcompetition/Join.css, client/src/pages/newcompetition/Join.jsx, client/src/pages/newcompetition/JoinCompetitionModal.jsx, client/src/pages/tournaments/Posts.jsx, client/src/store/social/friendApiSlice.js, client/src/store/social/friendSlice.js
1. Fixed refetching on Friends page so that when friends are accepted, rejected, removed, they shall be dynamically added or deleted accordingly;
2. Limited styling of Friends page components;
3. Commented out unused features for production
=> tidy up unused features, fix re-rendering on friends page

api/config/initializers/cors.rb, client/src/components/Header.css, client/src/pages/account/CompetitionCard.css, client/src/pages/account/CompetitionCard.jsx, client/src/pages/account/MainFeed.css, client/src/pages/account/Profile.css, client/src/pages/account/RecentWorkouts.jsx, client/src/pages/account/Sidebar.css, client/src/pages/friend/FriendCard.jsx, client/src/pages/friend/PendingFriendCard.jsx, client/src/pages/friend/SearchFriendResult.jsx, client/src/pages/newcompetition/Join.css, client/src/pages/newcompetition/NewCompetition.css, client/src/pages/tournaments/CompetitionPage.css, client/src/pages/tournaments/PostCard.css, client/src/pages/tournaments/Posts.jsx, client/src/pages/tournaments/Record.jsx
Addresses Issue #130 
Improved mobile responsiveness - resized max-widths to fit screen size so that all content fit on the screen on resize
=> continue styling for mobile responsiveness

client/src/components/Layout.jsx, client/src/pages/newcompetition/Join.css, client/src/pages/newcompetition/Join.jsx, client/src/pages/newcompetition/JoinCompetitionModal.jsx, client/src/pages/newcompetition/NewCompetition.css
styled join a comp to make the form look a little more sleek
=> styled join.css

api/app/channels/messages_channel.rb, api/app/controllers/messages_controller.rb, api/app/models/message.rb, api/app/models/user.rb, api/app/serializers/message_serializer.rb, api/config/routes.rb, api/db/migrate/20230526164606_create_messages.rb, api/db/migrate/20230526190022_add_user_referece_to_message.rb, api/db/schema.rb, client/package-lock.json, client/src/App.jsx, client/src/components/Header.jsx, client/src/pages/chat/Messages.css, client/src/pages/chat/Messages.jsx
1. Created messages model, channel, controller, serializer, routes
2. in messages model message broadcast after creation added
3. chat page in the client created
4. added route to the chat in client
5. web socket connections to server established 
Everyone welcome to contribute!
=> chat feature created

client/src/pages/chat/Messages.jsx
1.reload of previous push, because merged into main by mistake
=> ws changed

client/src/pages/chat/Messages.jsx
1. Changed fetching messages to heroku backend
=> changed fetching messages to test chat

api/config/initializers/cors.rb, client/src/app/api/apiSlice.js
Updated CORS.rb to include netlify preview and main URL origins. This should allow testing the preview builds before merging to production.
This address issues #155
=> Netlify preview cors error

api/config/cable.yml
1. cable.yml production adapter changed to postrges
=> cable yml adapter in production changed to postgres

api/app/controllers/posts_controller.rb, api/app/controllers/workouts_controller.rb, client/src/pages/tournaments/Record.jsx
1. Comment out action cable lines in post_controller and workouts_controller
2. Add back onChange and name attributes to Input element in Record.jsx (lines 118 - 119)
=> fix accident line deletions. Comment out non-used action cable code
